#ifndef TOKEN_ID_H
#define TOKEN_ID_H


typedef enum {
  TOKEN_WHITE_SPACE,
  TOKEN_KEYWORD,
  TOKEN_TYPE_NAME,
  TOKEN_IDENTIFIER,
  TOKEN_COMMENT,
  TOKEN_COLON,
  TOKEN_COMMA,
  TOKEN_BRACKET_OPEN,
  TOKEN_BRACKET_CLOSE,
  TOKEN_OPERATOR,
  TOKEN_STRING,
  TOKEN_FLOAT,
  TOKEN_INT,
  TOKEN_EXPRESSION_SEPARATOR,

  TOKENS_COUNT,

  TOKEN_UNKNOWN,
} TokenId;

#endif // TOKEN_ID_H
